name: Task 2

on:
  push:
    branches:
      - main
    paths:
      - task2/**

env:
  NAME: "task2-website"

jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: remove old container
        run: docker rm -f ${{ env.NAME }} || true
      - name: build image
        run: docker build -t ${{ env.NAME }}:1.0 task1
      - name: Run new container
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8081:80 \
          --name ${{ env.NAME }} \
          ${{ env.NAME }}:1.0