name: Task 5

on:
  push:
    branches:
      - main
    paths:
      - task5/**

env:
  NAME: task5

jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Determine Color
        run: |
          if docker ps --format '{{.Names}}' | grep -q "${{ env.NAME }}-blue"
          then
            echo "COLOR=green" >> $GITHUB_ENV
            echo "OLD_COLOR=blue" >> $GITHUB_ENV
            echo "PORT=8081" >> $GITHUB_ENV
          else
            echo "COLOR=blue" >> $GITHUB_ENV
            echo "OLD_COLOR=green" >> $GITHUB_ENV
            echo "PORT=8080" >> $GITHUB_ENV
          fi

      - name: build image
        run: docker build -t ${{ env.NAME }}-website:latest ${{ env.NAME }}

      - name: New Container Blue
        if: ${{ env.COLOR == 'blue' }}
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8080:80 \
          --name ${{ env.NAME }}-${{ env.COLOR }} \
          ${{ env.NAME }}-website:latest

      - name: New Container Green
        if: ${{ env.COLOR == 'green' }}
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8081:80 \
          --name ${{ env.NAME }}-${{ env.COLOR }} \
          ${{ env.NAME }}-website:latest

      - name: Container Health Check
        run: |
          echo "HEALTHY=false" >> $GITHUB_ENV
          for i in {1..10}
          do
            if curl -sf http://localhost:${{ env.PORT }} 
            then
              echo "HEALTHY=true" >> $GITHUB_ENV
              exit 0
            fi
            sleep 2
          done

      - name: Rollback if Unhealthy
        if: ${{ env.HEALTHY == 'false' }}
        run: |
          docker rm -f ${{ env.NAME }}-${{ env.COLOR }} || true
      - name: Remove Old Container
      
        if: ${{ env.HEALTHY == 'true' }}
        run: |
          docker rm -f ${{ env.NAME }}-${{ env.OLD_COLOR }} || true