name: Task 3

on:
  push:
    tags:
      - v*
    paths:
      - task3/**

env:
  NAME: "task3-website"

jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: remove old container
        run: docker rm -f ${{ env.NAME }} || true
      - name: build image
        run: docker build -t ${{ env.NAME }}:1.0 task3
      - name: Run new container
        run: |
          docker run -d \
          --restart unless-stopped \
          -p 8080:80 \
          --name ${{ env.NAME }} \
          ${{ env.NAME }}:1.0